{application,httpoison,
             [{registered,[]},
              {description,"  Yet Another HTTP client for Elixir powered by hackney\n"},
              {applications,[kernel,stdlib,elixir,hackney]},
              {vsn,"0.7.0"},
              {modules,['Elixir.HTTPoison','Elixir.HTTPoison.AsyncChunk',
                        'Elixir.HTTPoison.AsyncEnd',
                        'Elixir.HTTPoison.AsyncHeaders',
                        'Elixir.HTTPoison.AsyncResponse',
                        'Elixir.HTTPoison.AsyncStatus',
                        'Elixir.HTTPoison.Base','Elixir.HTTPoison.Error',
                        'Elixir.HTTPoison.Response']}]}.